#!/usr/bin/env bash
#
# Bash script for provisioning the AEM author instances

set -e
set -x
# Configure Ubuntu Server with hostname mentioned in VagrantFile
function host_config(){
    export CLIENT_IP_ADDR=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | tail -1`
    export CLIENT_FQDN=`hostname`
    export CLIENT_NAME=`hostname | cut -d. -f 1 | tr '[:upper:]' '[:lower:]'`
    echo "Configuring /etc/hosts ..."
    echo "127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4" > /etc/hosts
    echo "::1       localhost localhost.localdomain localhost6 localhost6.localdomain6" >> /etc/hosts
    echo "$CLIENT_IP_ADDR    $CLIENT_FQDN $CLIENT_NAME" >> /etc/hosts
}

# Copy AEM Install Jar and Unpack. Copy Configs and Scripts
function install_aem(){
    export AEM_ROOT=/apps/aem/author
    export AEM_USER=aem
    export AEM_INSTALLABLE_JAR=cq-quickstart-6.3.0.jar
    echo "Creat AEM Install root directories"
    sudo apt-get install -y oracle-java8-set-default
    mkdir -p /apps/aem/author
    mkdir -p /apps/aem/java_tmp
    chmod 777 /apps/aem/java_tmp
    echo "Copying AEM Installable Jar file from share"
    cp /share/aem-software/$AEM_INSTALLABLE_JAR $AEM_ROOT/.
    cp /share/aem-software/license.properties $AEM_ROOT/.
    echo "Unpacking AEM Jar File"
    cd $AEM_ROOT 
    java -jar $AEM_ROOT/$AEM_INSTALLABLE_JAR -unpack
    echo "Unpack Complete"
    echo "Copy DocumentNodeStoreService.config from /share"
    mkdir -p $AEM_ROOT/crx-quickstart/install
    cp /share/aem-mongo-configs/63/org.apache.jackrabbit.oak.plugins.document.DocumentNodeStoreService.config $AEM_ROOT/crx-quickstart/install
    cp /share/aem-mongo-configs/63/org.apache.jackrabbit.oak.plugins.blob.datastore.FileDataStore.config $AEM_ROOT/crx-quickstart/install
    echo "Copying aem startup script"
    cp /share/aem-mongo-configs/63/start $AEM_ROOT/crx-quickstart/bin
    echo "Create the shared Datastore links"
    mkdir -p $AEM_ROOT/crx-quickstart/repository
    ln -s /share/aem63-mongo-fds $AEM_ROOT/crx-quickstart/repository/datastore 
   # echo "Set Folder Permissions for vagrant user"
   # sudo chown -R vagrant:vagrant /apps/aem
    echo "Copy AEM Init Scripts ,to start and stop aem"
    mkdir -p /etc/sysconfig
    cp /share/aem-scripts/aem-config /etc/sysconfig
    cp /share/aem-scripts/aem-init.sh /usr/local/bin
    chmod +x /usr/local/bin/aem-init.sh
}

function update_repo(){
    echo "Update Repositoryies"
    sudo apt-get update -y
}

function install_java(){
    echo "Install Java"
    sudo add-apt-repository -y ppa:webupd8team/java
    sudo apt-get update
    sudo apt-get -y upgrade
    echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections 
    echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
    sudo apt-get -y install oracle-java8-installer
}

host_config
update_repo
install_java
install_aem
echo "Provisioning AEM 6.3 Node is complete !"
echo "Next Step --> ssh into host, Start AEM Process"

