#!/usr/bin/env bash
#
# Bash script for provisioning the AEM author instances

set -e
set -x

function host_config(){
	export CLIENT_IP_ADDR=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | tail -1`
	export CLIENT_FQDN=`hostname`
	export CLIENT_NAME=`hostname | cut -d. -f 1 | tr '[:upper:]' '[:lower:]'`
	echo "Configuring /etc/hosts ..."
	echo "127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4" > /etc/hosts
	echo "::1       localhost localhost.localdomain localhost6 localhost6.localdomain6" >> /etc/hosts
	echo "$CLIENT_IP_ADDR    $CLIENT_FQDN $CLIENT_NAME" >> /etc/hosts
}

# Create mongod user and install root directory
function mongod_user_config(){
   adduser mongod
   ssh-keygen -b 1024 -f mongod -t dsa
   sudo mkdir -p /home/mongod/.ssh
   cat aem.pub | sudo tee -a /home/mongod/.ssh/authorized_keys
   sudo chmod 600 /home/mongod/.ssh/authorized_keys
   sudo chmod 700 /home/mongod/.ssh
   sudo chown -R mongod /home/mongod

}

function install_mongod(){
	echo "Install MongoDB Enterprise 3.2.11"
	sudo apt-get install -y --force-yes mongodb-enterprise=3.2.11 mongodb-enterprise-server=3.2.11 mongodb-enterprise-shell=3.2.11
	sudo killall mongod
	echo "Creating mongodb 'data' and 'logs' folders"
	mkdir -p /apps/mongodb/data/db
	mkdir -p /apps/mongodb/data/logs
	chown -R mongod:mongod /apps/mongodb
	echo "Copying the mongod.conf from share"
	cp /share/mongo-configs/mongod.conf /etc/
	echo "Host ip is being added to bind_ip of mongod.conf"
	export CLIENT_IP_ADDR=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | tail -1`
	sed -i -e "s/127.0.0.1/127.0.0.1,$CLIENT_IP_ADDR/g" /etc/mongod.conf
	echo "bindIp is modified" | cat /etc/mongod.conf | grep 'bindIp'
}

function add_mongo32_repo(){
	echo "Install MongoDB Enterprise 3.2 Repository"
	echo "deb http://repo.mongodb.com/apt/ubuntu "$(lsb_release -sc)"/mongodb-enterprise/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-enterprise.list
	sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
	echo "Update Repositories"
	sudo apt-get update -y
	echo "Installing MongoDB Enterprise Dependencies"
	sudo apt-get install -y libgssapi-krb5-2 libsasl2-2 libssl1.0.0 libstdc++6 snmp

}

function mongod_config(){
	echo "Disable THP - http://docs.mongodb.org/master/tutorial/transparent-huge-pages/"
	echo "
	#!/bin/sh
	### BEGIN INIT INFO
	# Provides:          disable-transparent-hugepages
	# Required-Start:    $local_fs
	# Required-Stop:
	# X-Start-Before:    mongod mongodb-mms-automation-agent
	# Default-Start:     2 3 4 5
	# Default-Stop:      0 1 6
	# Short-Description: Disable Linux transparent huge pages
	# Description:       Disable Linux transparent huge pages, to improve
	#                    database performance.
	### END INIT INFO

	case $1 in
	  start)
	    if [ -d /sys/kernel/mm/transparent_hugepage ]; then
	      thp_path=/sys/kernel/mm/transparent_hugepage
	    elif [ -d /sys/kernel/mm/redhat_transparent_hugepage ]; then
	      thp_path=/sys/kernel/mm/redhat_transparent_hugepage
	    else
	      return 0
	    fi

	    echo 'never' > ${thp_path}/enabled
	    echo 'never' > ${thp_path}/defrag

	    unset thp_path
	    ;;
	esac
	" > /etc/init.d/disable-transparent-hugepages
	sudo chmod 755 /etc/init.d/disable-transparent-hugepages
	sudo update-rc.d disable-transparent-hugepages defaults
	echo "Set LC_ALL=C to .profile"
	sudo echo "export LC_ALL=C" >> /home/mongod/.profile
}

function mongod_service(){
	echo "Creating mongod.service"
	echo "
	[Unit]
	Description=High-performance, schema-free document-oriented database
	After=network.target

	[Service]
	User=mongod
	ExecStart=/usr/bin/mongod --quiet --config /etc/mongod.conf

	[Install]
	WantedBy=multi-user.target
" > /etc/systemd/system/mongod.service
}

host_config
mongod_user_config
add_mongo32_repo
install_mongod
mongod_config
mongod_service

echo "Completed provisioning Mongo 3.2.11 Virtual Machine"
