Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = true
  config.vm.synced_folder "../share", "/share"

  (0..2).each do |i|

    config.vm.define "mongo-node#{i}" do |server|
      server.vm.provider "virtualbox" do |vb|
          vb.customize ["modifyvm", :id, "--cpus", "2"]
        vb.name = "mongo-node#{i}"
        vb.memory = 2048
      end
      server.vm.hostname = "mongo-node#{i}.aem.cluster"
      server.vm.network :private_network, ip: "192.168.23.10#{i}"
      server.vm.provision :shell, path: "provision-mongod", args: ENV['ARGS']
    end
  end
 
 (0..1).each do |i|
    config.vm.define "aem-node#{i}" do |server|
      server.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--cpus", "2"]
          vb.name = "aem-node#{i}"
          vb.memory = 4096
        end
      server.vm.hostname = "aem-node#{i}.aem.cluster"
      server.vm.network :private_network, ip: "192.168.63.11#{i}"
      server.vm.provision :shell, path: "provision-aem", args: ENV['ARGS']
    end
  end
end
