Vagrant.configure("2") do |config|
# using ubuntu , vagrant box update will keep it upto date
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = true
  # Set the timezone to the host timezone
  require 'time'
  timezone = 'Etc/GMT' + ((Time.zone_offset(Time.now.zone)/60)/60).to_s
  config.vm.provision :shell, :inline => %Q(
    if [ $(grep -c UTC /etc/timezone) -gt 0 ]
      then echo "#{timezone}" | sudo tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata
    fi
        )
# Setup the share between host and guest / vm
  config.vm.synced_folder "../share", "/share"
# Provision 3 Mongo Nodes
 (0..2).each do |i|

    config.vm.define "mongo32-node#{i}" do |server|
      server.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--cpus", "2"]
        vb.name = "mongo32-node#{i}"
        vb.memory = 2048
      end
      server.vm.hostname = "mongo32-node#{i}.aem.cluster"
      server.vm.network :private_network, ip: "192.168.23.10#{i}"
      server.vm.provision :shell, path: "provision-mongod", args: ENV['ARGS']
    end
  end
end
