Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = true
  config.vm.synced_folder "../share", "/share"
  # Set the timezone to the host timezone
  require 'time'
  timezone = 'Etc/GMT' + ((Time.zone_offset(Time.now.zone)/60)/60).to_s
  config.vm.provision :shell, :inline => %Q(
    if [ $(grep -c UTC /etc/timezone) -gt 0 ]
      then echo "#{timezone}" | sudo tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata
    fi
	)  
# Provision 2 AEM Nodes 
(0..1).each do |i|
    config.vm.define "aem62-node#{i}" do |server|
      server.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--cpus", "2"]
          vb.name = "aem62-node#{i}"
          vb.memory = 4096
        end
      server.vm.hostname = "aem62-node#{i}.aem.cluster"
      server.vm.network :private_network, ip: "192.168.62.11#{i}"
      server.vm.provision :shell, path: "provision-aem", args: ENV['ARGS']
    end
  end
end
