Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = true
  config.vm.synced_folder "../share", "/share"
  # Set the timezone to the host timezone
  require 'time'
  timezone = 'Etc/GMT' + ((Time.zone_offset(Time.now.zone)/60)/60).to_s
  config.vm.provision :shell, :inline => %Q(
    if [ $(grep -c UTC /etc/timezone) -gt 0 ]
      then echo "#{timezone}" | sudo tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata
    fi
	)  
    # Provision 1 Server with 2 AEM Runtimes and 3 Mongo ( PSS) 
    config.vm.define "aem63-cluster" do |server|
      server.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--cpus", "4"]
          vb.name = "aem63-cluster"
          vb.memory = 10240
        end
      server.vm.hostname = "aem63-cluster"
      server.vm.network :private_network, ip: "192.168.63.100"
      server.vm.provision :shell, path: "provision-aem-cluster", args: ENV['ARGS']
 end
end
